spring.application.name=cultura-viva

server.port=8080

# Desactivar cache durante el desarrollo
spring.thymeleaf.cache=false

# Mostrar mensajes de error durante el desarrollo
server.error.include-message=always

# Configuracion temporal: iniciar sin MySQL ni JPA
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.data.jpa.autoconfigure.DataJpaRepositoriesAutoConfiguration