spring.application.name=cultura-viva

server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false

# Mostrar mensajes de error durante el desarrollo
server.error.include-message=always

# Conexion a MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cultura_viva?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=America/Lima}
spring.datasource.username=${DB_USERNAME:cultura_viva_app}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Codificacion
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true